apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 148761663673.dkr.ecr.ap-northeast-2.amazonaws.com/
  newName: 148761663673.dkr.ecr.ap-northeast-2.amazonaws.com/
  newTag: a63775e1
- name: 148761663673.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 148761663673.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 69f71070
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
